### PR TITLE
docs: fix image path && Richard Feynman

### PR DESCRIPTION
**Pull request by c0utin**
# Changelog 

* Introduction ch00/introduction

### CODE REVIEW

**Review by misterclayt0n — CHANGES_REQUESTED** [review]
To the "Why this book exists" topic, add a series of topics/subjects that exist outside of web development, give examples of such projects and technologies. Things like Turso, Zed, Bun, Linux, and so on.

**Comment by c0utin** [comment]
@misterclayt0n merge?

**Comment by c0utin** [comment]
@misterclayt0n

**Comment by c0utin** [comment]
@misterclayt0n

**Comment by c0utin** [comment]
@misterclayt0n

**Comment by c0utin** [comment]
@misterclayt0n

**Review by misterclayt0n — APPROVED** [review]

**Pull request merged**
